name: auto-merge

on:
  push:
    branches: [ master ]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
