name: Deploy on CI

on:
  push:
    branches: [ master ]

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn
      - name: Clean
        run: npx rimraf ./build

  code-quality:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: lint
        run: yarn eslint:fix

  test:
    needs: code-quality
    runs-on: ubuntu-latest
    steps:
      - name: lint
        run: yarn test

  build:
    needs: code-quality
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: yarn build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
